<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGIG.Entidades\SGIG.Entidades.csproj" />
    <ProjectReference Include="..\SGIG.Negocio\SGIG.Negocio.csproj" />
  </ItemGroup>

</Project>
