<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGIG.Entidades\SGIG.Entidades.csproj" />
    <ProjectReference Include="..\SGIG.Datos\SGIG.Datos.csproj" />
  </ItemGroup>

</Project>
